---

services:
  alloy:
    image: "grafana/alloy:latest"
    ports:
      - "127.0.0.1:12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./targets.yml:/etc/alloy/targets.yml
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
  sherlock:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - REDFISH_USERNAME=${REDFISH_USERNAME:-admin}
      - REDFISH_PASSWORD=${REDFISH_PASSWORD:-password}
      - REDFISH_INSECURE=true
      - LOG_LEVEL=debug
    ports:
      - "127.0.0.1:9291:9290"
    command:
      - ./sherlock
      - --web.listen-address=0.0.0.0:9290
      - --web.telemetry-path=/metrics
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9290/"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  alloy-data:
